name: Workflow Commands

on:
    workflow_dispatch:
    push:

jobs:
  commands_job:
    runs-on: [production,linux]
    steps:
      - name: Set environment variable with "key" as "foo" and "value" as "bar" 
        run: echo "foo=bar" >> $GITHUB_ENV
